<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>

<script type="text/javascript">
    (async function () {
        await CefSharp.BindObjectAsync("app", "bound");
    })();
</script>
    
 <script>
        (function() {

            var $allVideos = $("div[id^='player'], object, embed"),
            $fluidEl = $("figure");

	        $allVideos.each(function() {

	          $(this)
	            // jQuery .data does not work on object/embed elements
	            .attr('data-aspectRatio', this.height / this.width)
	            .removeAttr('height')
	            .removeAttr('width');

	        });

	        $(window).resize(function() {

	          var newWidth = $fluidEl.width();
	          $allVideos.each(function() {

	            var $el = $(this);
	            $el
	                .width(newWidth)
	                .height(newWidth * $el.attr('data-aspectRatio'));

	          });

	        }).resize();

        });
    </script>

    <style>
        .embed-container {
            position: relative;
            padding-bottom: 56.25%;
            height: 0;
            overflow: hidden;
            max-width: 100%;
        }

        .embed-container iframe, .embed-container object, .embed-container embed {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
        }

        .unselectable {
           -moz-user-select: -moz-none;
           -khtml-user-select: none;
           -webkit-user-select: none;

           /*
             Introduced in IE 10.
             See http://ie.microsoft.com/testdrive/HTML5/msUserSelect/
           */
           -ms-user-select: none;
           user-select: none;
        }
    </style>
	
	
	<div class='embed-container'>
        <div id="player" class="unselectable"></div>
	</div>
	
    <script>
	  var player;
	  
	  function spawnPlayer(videoID){
	  
		  var homeTag = document.getElementsByTagName('iframe')[0];
		  
		  
		  var tag = document.createElement('script');
		  
		  tag.src = "https://www.youtube.com/iframe_api";
		  var firstScriptTag = document.getElementsByTagName('script')[0];
		  firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

		  
	  }
      
      function onYouTubeIframeAPIReady() {
        player = new YT.Player('player', {
          height: '390',
          width: '640',
          videoId: videoID,
          events: {
              'onReady': onPlayerReady,
              'onStateChange': onPlayerStateChange,
              'onError': onPlayerError
          }
        });
      }

      function onPlayerError(event) {
          if (event.data == 150 || event.data == 101)
          {
              app.errorHandle();
          }
      }

      function onPlayerReady(event) {
        event.target.playVideo();
      }

      function onPlayerStateChange(event) {
          if (event.data == YT.PlayerState.ENDED) {
              app.getNextVideo();
			}
		  if (event.data == -1){ //Not started - no const for this
			 player.playVideo();
			 setTimeout(isPlaying, 300);
		  }
		  
      }

      function stopVideo() {
        player.stopVideo();
      }
	  
	  function changeVideo(a){
		player.loadVideoById({videoId: a});
		player.playVideo();
	  }

	  function isPlaying() {
	      var state = player.getPlayerState();
		  if (state == -1 || state == 2){
			player.playVideo();
			setTimeout(isPlaying, 300);
		  }
	  }
    </script>
	
	<iframe src="home.html" style="position:fixed; top:0; left:0; bottom:0; right:0; width:100%; height:100%; border:none; margin:0; padding:0; overflow:hidden; z-index:999999;" />
</body>
</html>